package com.kalshi.client.auth;

import com.kalshi.client.exception.AuthenticationException;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.KeyFactory;
import java.security.PrivateKey;
import java.security.Signature;
import java.security.spec.MGF1ParameterSpec;
import java.security.spec.PKCS8EncodedKeySpec;
import java.security.spec.PSSParameterSpec;
import java.util.Base64;

/**
 * Handles authentication for Kalshi API requests using RSA-PSS with SHA256.
 *
 * The signature is generated by signing: timestamp + HTTP_METHOD + path
 * (path without query parameters)
 */
public class KalshiAuthenticator {

    private final String apiKeyId;
    private final PrivateKey privateKey;

    /**
     * Create authenticator with API key ID and private key.
     *
     * @param apiKeyId The API key ID (KALSHI-ACCESS-KEY)
     * @param privateKey The RSA private key for signing
     */
    public KalshiAuthenticator(String apiKeyId, PrivateKey privateKey) {
        this.apiKeyId = apiKeyId;
        this.privateKey = privateKey;
    }

    /**
     * Create authenticator from API key ID and private key PEM string.
     *
     * @param apiKeyId The API key ID
     * @param privateKeyPem The private key in PEM format
     * @return KalshiAuthenticator instance
     */
    public static KalshiAuthenticator fromPem(String apiKeyId, String privateKeyPem) {
        try {
            PrivateKey privateKey = loadPrivateKeyFromPem(privateKeyPem);
            return new KalshiAuthenticator(apiKeyId, privateKey);
        } catch (Exception e) {
            throw new AuthenticationException("Failed to load private key from PEM", e);
        }
    }

    /**
     * Create authenticator from API key ID and private key file path.
     *
     * @param apiKeyId The API key ID
     * @param privateKeyPath Path to the private key PEM file
     * @return KalshiAuthenticator instance
     */
    public static KalshiAuthenticator fromFile(String apiKeyId, Path privateKeyPath) {
        try {
            String pemContent = Files.readString(privateKeyPath);
            return fromPem(apiKeyId, pemContent);
        } catch (Exception e) {
            throw new AuthenticationException("Failed to load private key from file: " + privateKeyPath, e);
        }
    }

    /**
     * Get the API key ID.
     */
    public String getApiKeyId() {
        return apiKeyId;
    }

    /**
     * Generate authentication headers for a request.
     *
     * @param method HTTP method (GET, POST, DELETE, etc.)
     * @param path Request path (without query parameters)
     * @return AuthHeaders containing all required authentication headers
     */
    public AuthHeaders generateHeaders(String method, String path) {
        long timestamp = System.currentTimeMillis();
        String signature = sign(timestamp, method, path);
        return new AuthHeaders(apiKeyId, String.valueOf(timestamp), signature);
    }

    /**
     * Sign the request using RSA-PSS with SHA256.
     *
     * @param timestamp Request timestamp in milliseconds
     * @param method HTTP method
     * @param path Request path (without query parameters)
     * @return Base64-encoded signature
     */
    public String sign(long timestamp, String method, String path) {
        try {
            // Message format: timestamp + HTTP_METHOD + path
            String message = timestamp + method.toUpperCase() + path;
            byte[] messageBytes = message.getBytes(StandardCharsets.UTF_8);

            // Use RSA-PSS with SHA256
            Signature signature = Signature.getInstance("RSASSA-PSS");

            // Configure PSS parameters to match Kalshi's requirements
            PSSParameterSpec pssSpec = new PSSParameterSpec(
                "SHA-256",                    // Hash algorithm
                "MGF1",                       // Mask generation function
                MGF1ParameterSpec.SHA256,     // MGF parameters
                32,                           // Salt length (digest length)
                1                             // Trailer field
            );
            signature.setParameter(pssSpec);

            signature.initSign(privateKey);
            signature.update(messageBytes);
            byte[] signatureBytes = signature.sign();

            return Base64.getEncoder().encodeToString(signatureBytes);
        } catch (Exception e) {
            throw new AuthenticationException("Failed to sign request", e);
        }
    }

    /**
     * Load a private key from PEM format.
     */
    private static PrivateKey loadPrivateKeyFromPem(String pem) throws Exception {
        // Remove PEM headers and whitespace
        String privateKeyContent = pem
            .replace("-----BEGIN PRIVATE KEY-----", "")
            .replace("-----END PRIVATE KEY-----", "")
            .replace("-----BEGIN RSA PRIVATE KEY-----", "")
            .replace("-----END RSA PRIVATE KEY-----", "")
            .replaceAll("\\s+", "");

        byte[] keyBytes = Base64.getDecoder().decode(privateKeyContent);
        PKCS8EncodedKeySpec keySpec = new PKCS8EncodedKeySpec(keyBytes);
        KeyFactory keyFactory = KeyFactory.getInstance("RSA");
        return keyFactory.generatePrivate(keySpec);
    }

    /**
     * Container for authentication headers.
     */
    public static class AuthHeaders {
        private final String accessKey;
        private final String timestamp;
        private final String signature;

        public AuthHeaders(String accessKey, String timestamp, String signature) {
            this.accessKey = accessKey;
            this.timestamp = timestamp;
            this.signature = signature;
        }

        public String getAccessKey() {
            return accessKey;
        }

        public String getTimestamp() {
            return timestamp;
        }

        public String getSignature() {
            return signature;
        }

        @Override
        public String toString() {
            return "AuthHeaders{" +
                    "accessKey='" + accessKey + '\'' +
                    ", timestamp='" + timestamp + '\'' +
                    ", signature='***'" +
                    '}';
        }
    }
}
